spring:
  application:
    name: dividendfund-financial

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dividendfund;DB_CLOSE_DELAY=-1
    username: sa
    password: 1111

  redis:
    host: localhost
    port: 6379

  jwt:
    secret: ZGl2aWRlbmQtand0LXNlY3JldC1rZXkK

  scheduler:
    scrap:
      yahoo: "0 0 0 * * *"
